config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'links#index'

  get '/tagged', to: "links#tagged", as: :tagged

  resources :links
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user

  validates :link, presence: true

  acts_as_taggable_on :tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :links       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!

  def index
    @links = current_user.links.page(params[:page]).per(6)

    @user_tags = user_tags
  end

  def new
    @link = Link.new
    @user_tags = user_tags
  end

  def create
    @link = Link.new(link_params)
    @link.user = current_user

    if @link.save
      redirect_to links_path, notice: "Link successfully added"
    else
      render :new
    end
  end

  def edit
    @link = current_user.links.find(params[:id])
    @user_tags = user_tags
  end

  def update
    @link = Link.find(params[:id])

    if @link.user == current_user
      if @link.update(link_params)
        redirect_to links_path, notice: "Link successfully updated"
      else
        render :edit
      end
    else
      redirect_to links_path
    end
  end

  def destroy
    @link = current_user.links.find(params[:id])

    if @link.user == current_user && @link.destroy
      redirect_to links_path, alert: "Link successfully deleted"
    else
      render :edit
    end
  end

  def tagged
    @user_tags = user_tags

    if params[:tag].present?
      @links = current_user.links.tagged_with(params[:tag]).page(params[:page]).per(6)
      @tag = params[:tag]
    else
      @links = current_user.links.page(params[:page]).per(6)
    end

    render "links/index"
  end

  private

  def link_params
    params.require(:link).permit(:link, :link_descrition, :tag_list)
  end

  def user_tags
    ActiveRecord::Base.connection.execute(
      "SELECT * FROM tags "\
      "inner join taggings "\
      "on tags.id = taggings.tag_id "\
      "inner join links on taggings.taggable_id = links.id "\
      "where links.user_id = #{current_user.id}"
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for_flash(flash_type)
    case flash_type
    when 'alert'
      'alert-danger'
    when 'notice'
      'alert-success'
    else
      flash_type.to_s
    end
  end
end

app/views/layouts/_flash.html.haml
.container{ style: 'margin-top: 10px'}
  - flash.each do |type, msg|
    %div{ class: "alert #{bootstrap_class_for_flash(type)} alert-dismissable fade show", style:"left: -51px;"}
      = msg
      %button.close{"data-dismiss" => "alert"} x

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .collapse.navbar-collapse
    .navbar-brand
      Links Manager Service
    %ul.navbar-nav.mr-auto
      %li.nav-item.active
        = link_to 'Add link', new_link_path, method: :get, class: "nav-link"
      %li.nav-item.active{ style: 'margin-left: 10px'}
        = link_to 'Links list', links_path, method: :get, class: "nav-link"
      - if current_user.role == 'admin'
        %li.nav-item.active{ style: 'margin-left: 10px'}
          = link_to 'Admin panel', '/admin', method: :get, class: "nav-link"
      - else
    .nav-item.active.text-righ
      = button_to 'Sing out', destroy_user_session_path, method: :delete, class: "btn btn-outline-dark"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title LinksManagerService
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    - if user_signed_in?
      = render 'layouts/nav'
    - else
    .container
      = render 'layouts/flash', flash: flash
      .row
        .col-md-9
          = yield
        .col-md-2
          - if user_signed_in?
            = render 'links/tags'
          - else

app/views/links/_form.html.haml
.container{ style: 'margin-top: 10px'}
  .list-group
    .list-group-item
      = simple_form_for @link do |f|
        %form
          .form-group
            %h5
              Add your link:
          .form-group
            = f.input :link, input_html: { :class => "form-control #{'is-invalid' if f.object.errors[:link].any?}" }, placeholder: "Enter link without https://"
          .form-group
            = f.input :tag_list, input_html: { :class => 'form-control' }, placeholder: "Enter tag"
          .form-group
            = f.input :link_descrition, input_html: { :class => 'form-control' }, placeholder: "Enter description"
          %p
          - if @link.persisted?
            = f.button :submit, label: 'Update link', class:"btn btn-outline-success"
          - else
            = f.button :submit, label: 'Save link', class:"btn btn-outline-success"

app/views/links/_tags.html.haml
.container{ style: 'margin-top: 10px'}
  .list-group
    - if @user_tags.present? && @user_tags.any?
      .list-group-item
        = 'Your tags:'
      .nav.nav-pills.nav-stacked.scrollClass
        - @user_tags.each do |tag|
          = link_to tag['name'], tagged_path(tag: tag['name']), class: "list-group-item list-group-item-action"
    - else
      .list-group-item
        = 'Sorry but you don`t have any tag'

app/views/links/edit.html.haml
= render 'links/form' 

app/views/links/index.html.haml
- if @tag.present?
  .container{ style: 'margin-top: 10px'}
    %h4
      = "Your filter by this tag: #{@tag}"
-else
.row
  - @links.each do |link|
    .card.col-md-5.mr-3{ style: 'margin-top: 10px'}
      .card-body
        %h5.card-title
          = link_to "#{link.link}", "https://#{link.link}", target: '_blank'
        %h6.card-subtitle.mb-2.text-muted
          = 'Tags:'
          - if link.tag_list.present?
            - link.tag_list.each do |tag|
              = link_to tag, tagged_path(tag: tag)
          -else
            = 'tag is empty'
        %p.card-text
          = link.link_descrition
        .row
          .col-sm
            = button_to 'Update link', edit_link_path(link), method: :get, class: "card-link btn btn-outline-primary"
          .col-sm
            = button_to 'Delete link', link_path(link), method: :delete, class: "card-link btn btn-outline-danger"
.d-flex.p-2.justify-content-center{ style: 'margin-top: 10px'}
  = paginate @links, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm", nav_class: "d-inline-b"

app/views/links/new.html.haml
= render 'links/form'